accelerator: gpu
devices:
- 0
log_dir: ./log
resume: null
ckpt_path: ./checkpoints/epoch=20-step=109367.ckpt
dataset_config:
  train_kwargs:
    batch_size: 32
    cut_duration:
    - 5.0
    - 5.0
    enroll_duration: 5.0
    num_workers: 16
    prefetch: 32
    samples_per_epoch: 1000000
    simulation_config: ./conf/simulation_train.yaml
    speech_scp_base_dir: /voxbox
    speech_scp_path:
    - /emilia_zh_800000_subset.scp
    - /librispeech.scp
    - /mls_english_300000_subset.scp
    noise_scp_path:
    - /train/train_2021_dns2_noises.scp
    - /train/fsd50k.scp
    - /train/wham.scp
    - /train/train_DESED_noise.scp
    - /train/demand.scp
    - /train/musan_noise.scp
    - /train/train_disco_noises.scp
    - /train/MUSDB18-HQ.scp
    - /train/TUT_UAS_2018.scp
    rir_scp_path: /rir_scp/simulated_rirs.scp
  val_kwargs:
    batch_size: 1
    cut_duration:
    - 5.0
    - 5.0
    enroll_duration: 5.0
    num_workers: 1
    prefetch: 1
    samples_per_epoch: 1000
    simulation_config: ./conf/simulation_train.yaml
    speech_scp_base_dir: /voxbox
    speech_scp_path:
    - /emilia_zh_800000_subset.scp
    - /librispeech.scp
    - /mls_english_300000_subset.scp
    noise_scp_path:
    - /train/train_2021_dns2_noises.scp
    - /train/fsd50k.scp
    - /train/wham.scp
    - /train/train_DESED_noise.scp
    - /train/demand.scp
    - /train/musan_noise.scp
    - /train/train_disco_noises.scp
    - /train/MUSDB18-HQ.scp
    - /train/TUT_UAS_2018.scp
    rir_scp_path: /rir_scp/simulated_rirs.scp
  test_kwargs:
    batch_size: 1
    num_workers: 1
    prefetch: 1
    mode: se
    data_enroll_dir: null
    enroll_duration: 5.0
    data_src_dir: ./AudioSamples/SR/noisy
    data_tgt_dir: ./AudioSamples/SR/clean
max_epochs: 100
val_check_interval: 0.5
gradient_clip_val: 5.0
opt:
  lr: 0.0005
sch:
  warmup_steps: 2000
  step_decay: 0.99998
  min_factor: 0.02
codec_ckpt_dir: ./checkpoints
stft_config:
  hop_length: 320
  win_length: 640
  n_fft: 640
  n_mels: 80
llm_config:
  num_tasks: 3
  task_map:
    se: 0
    tse: 1
    rtse: 2
  feats_dim: 768
  llm_base_config:
    cond_dim: 80
    global_size: 4096
    semantic_size: 8192
    hidden_size: 512
    num_layers: 12
    num_attention_heads: 8
    dropout_p: 0.1
    max_position_embeddings: 4096
    label_smoothing: 0.1
    conformer_params:
      num_layers: 6
      dim: 512
      heads: 8
      dim_head: 64
      depthwise_conv_kernel_size: 31
      ff_mult: 4
      dropout: 0.1
      qk_norm: null
      pe_attn_head: 1
